{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "1caca91e-df2d-4a05-a6bf-d20f39fe9a10",
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import string\n",
    "import re\n",
    "import nltk\n",
    "from gensim.models import Word2Vec\n",
    "import numpy as np\n",
    "from sklearn.metrics.pairwise import cosine_similarity\n",
    "\n",
    "# Paste your existing code here\n",
    "#!/usr/bin/env python\n",
    "# coding: utf-8\n",
    "\n",
    "# # Whisky Recommender\n",
    "# <b>Tentative Workflow</b>\n",
    "# 1. Extract Nose, Taste, Finish text\n",
    "# 2. Combine text from Step into 1 column\n",
    "# 3. Remove punctuations and stopwords from output of Step 2\n",
    "# 4. Tokenize output of Step 3\n",
    "# 5. Lemmatize output of Step 4\n",
    "# 6. Create W2V vectors on output of Step 5\n",
    "# 7. Create W2V vector for a test review\n",
    "# 8. Print the title of the vector in Step 6 that is closest to the vector in Step 7\n",
    "\n",
    "# ## Import Libraries\n",
    "\n",
    "# In[1]:\n",
    "\n",
    "\n",
    "import pandas as pd\n",
    "pd.set_option('display.max_rows', 500)\n",
    "pd.set_option('display.max_columns', 500)\n",
    "pd.set_option('max_colwidth', 2000)\n",
    "\n",
    "\n",
    "# ## Load Data\n",
    "\n",
    "# In[2]:\n",
    "\n",
    "\n",
    "data = pd.read_csv(\"whisky_clean.csv\")\n",
    "\n",
    "# For Machine Learning, we would only need the Title and Combined Text columns\n",
    "data = data[['Title', 'Nose', 'Taste', 'Finish']]\n",
    "\n",
    "# This ensures that even if there are non-string values in the columns, they will be converted to strings before concatenation.\n",
    "data['combined_text'] = data['Nose'].astype(str) + \" \" + data['Taste'].astype(str) + \" \" + data['Finish'].astype(str)\n",
    "\n",
    "# Check if the text gets combined correctly for each review\n",
    "#data.head()\n",
    "\n",
    "\n",
    "# ## Preprocess Data\n",
    "\n",
    "# ### Remove Punctuations\n",
    "\n",
    "# In[3]:\n",
    "\n",
    "\n",
    "# string.punctuation comprises of a list of all punctuations\n",
    "string.punctuation\n",
    "\n",
    "\n",
    "# In[4]:\n",
    "\n",
    "\n",
    "def remove_punct(text):\n",
    "    # store character only if it is not a punctuation\n",
    "    text_nopunct = \"\".join([char for char in text if char not in string.punctuation])\n",
    "    return text_nopunct\n",
    "\n",
    "data['combined_text_clean'] = data['combined_text'].apply(lambda x: remove_punct(x))\n",
    "\n",
    "#data.head()\n",
    "\n",
    "\n",
    "# ### Tokenization\n",
    "\n",
    "# In[5]:\n",
    "\n",
    "\n",
    "def tokenize(text):\n",
    "    # Matches any character that is neither alphanumeric nor underscore\n",
    "    # Add a + just in case there are 2 or more spaces between certain words\n",
    "    tokens = re.split('\\W+', text)\n",
    "    return tokens\n",
    "\n",
    "data['combined_text_tokenized'] = data['combined_text_clean'].apply(lambda x: tokenize(x.lower()))\n",
    "\n",
    "#data.head()\n",
    "\n",
    "\n",
    "# ### Remove Stopwords\n",
    "\n",
    "# In[6]:\n",
    "\n",
    "\n",
    "import nltk\n",
    "\n",
    "# NLTK(Natural Language Toolkit) in python has a list of stopwords stored in 16 different languages.\n",
    "stopword = nltk.corpus.stopwords.words('english')\n",
    "\n",
    "# if you get an error with the above code, comment the code above and run this & follow below directions:\n",
    "# nltk.download()\n",
    "\n",
    "\n",
    "# <b>If you ran into issues with the above:</b>\n",
    "# \n",
    "# 1. Run <code>nltk.download()</code>. A new screen will pop up outside your Jupyter notebook. (It may be hidden behind other windows.)\n",
    "# 2. Once this box opens up, click <code>all</code>, then <code>download</code>. Once this is done, restart your Jupyter notebook and try running the cell above again.\n",
    "\n",
    "# In[7]:\n",
    "\n",
    "\n",
    "def remove_stopwords(tokenized_list):\n",
    "    # Store in text only if word is not found in stopword i.e. it is not a stopword\n",
    "    text = [word for word in tokenized_list if word not in stopword]\n",
    "    return text\n",
    "\n",
    "data['combined_text_nostop'] = data['combined_text_tokenized'].apply(lambda x: remove_stopwords(x))\n",
    "\n",
    "#data.head()\n",
    "\n",
    "\n",
    "# ### Lemmatization\n",
    "\n",
    "# In[8]:\n",
    "\n",
    "\n",
    "# if you get an error with this cell, uncomment the line of code and re-run this cell\n",
    "#nltk.download('wordnet')\n",
    "\n",
    "wn = nltk.WordNetLemmatizer()\n",
    "\n",
    "def lemmatizing(tokenized_text):\n",
    "    # return list of all lemmatized words for their corresponding words in tokenized_text\n",
    "    text = [wn.lemmatize(word) for word in tokenized_text]\n",
    "    return text\n",
    "\n",
    "data['combined_text_lemmatized'] = data['combined_text_nostop'].apply(lambda x: lemmatizing(x))\n",
    "\n",
    "#data.head()\n",
    "\n",
    "\n",
    "# ## Train Model\n",
    "\n",
    "# In[9]:\n",
    "\n",
    "\n",
    "# Train the word2vec model\n",
    "# vector_size = size of word vector. size input all dimensions that meet window param value\n",
    "# window = number of words before and after the focus word that will be considered as context\n",
    "# min_count = number of times word must appear in corpus in order to create a word vector\n",
    "### Important - Model will only be trained on words that meet min_count so it may not learn all words as a result\n",
    "w2v_model = Word2Vec(data[\"combined_text_lemmatized\"], vector_size=100, window=5, min_count=2)\n",
    "\n",
    "\n",
    "# In[10]:\n",
    "\n",
    "\n",
    "# create a list to store the average of all word vectors for each row of data\n",
    "review_vect_list = []\n",
    "\n",
    "# Iterate through each row in X train data\n",
    "for index, row in data.iterrows():\n",
    "\n",
    "    # Create a Word2Vec vector for each row (review) in train data \n",
    "    # By applying the W2V model on each word of each review, we get the word vector (embedding) for each word\n",
    "    # Each row (review) will be represented by average of all vectors of all words in each row that model has trained on\n",
    "    model_vector = (np.mean([w2v_model.wv.get_vector(token) for token in row['combined_text_lemmatized'] if token in w2v_model.wv], axis=0)).tolist()\n",
    "\n",
    "    # Check if the line exists else it is vector of zeros\n",
    "    if type(model_vector) is list:  \n",
    "        review_vect_list.append(model_vector)\n",
    "    else:\n",
    "        review_vect_list.append([str(0) for i in range(100)])\n",
    "        \n",
    "word2vec_df = pd.DataFrame(review_vect_list)\n",
    "\n",
    "\n",
    "# In[11]:\n",
    "\n",
    "\n",
    "# Add 'sentence_vector' column to data DataFrame\n",
    "data['sentence_vector'] = word2vec_df.values.tolist()\n",
    "\n",
    "\n",
    "# ## Make Predictions\n",
    "\n",
    "# In[12]:\n",
    "\n",
    "\n",
    "# Function to get word vectors\n",
    "def get_word_vectors(sentence):\n",
    "    word_vectors = []\n",
    "    for word in sentence.split():\n",
    "        if word in w2v_model.wv:\n",
    "            word_vectors.append(w2v_model.wv[word])\n",
    "    return word_vectors\n",
    "\n",
    "# Function to calculate sentence vector by averaging word vectors\n",
    "def get_sentence_vector(sentence):\n",
    "    word_vectors = get_word_vectors(sentence)\n",
    "    if not word_vectors:\n",
    "        return np.zeros(w2v_model.vector_size)\n",
    "    return np.mean(word_vectors, axis=0)\n",
    "\n",
    "# Function to find the closest sentence to the input text and calculate the cosine similarity percentage\n",
    "def find_closest_sentence(input_text, data):\n",
    "    input_vector = get_sentence_vector(input_text)\n",
    "    max_similarity = -1\n",
    "    closest_sentence = None\n",
    "    closest_similarity_percent = 0\n",
    "    \n",
    "    for index, row in data.iterrows():\n",
    "        sentence_vector = row['sentence_vector']\n",
    "        similarity = cosine_similarity([input_vector], [sentence_vector])[0][0]\n",
    "        if similarity > max_similarity:\n",
    "            max_similarity = similarity\n",
    "            closest_sentence = row['Title']\n",
    "            closest_similarity_percent = similarity  # Save the similarity percentage\n",
    "\n",
    "    return closest_sentence, closest_similarity_percent\n",
    "\n",
    "    # Convert cosine similarity to percentage\n",
    "    closest_similarity_percent = \"{:.2f}\".format(closest_similarity * 100)\n",
    "    \n",
    "    return closest_sentence, closest_similarity_percent\n",
    "\n",
    "\n",
    "# In[13]:\n",
    "\n",
    "\n",
    "# Define the food choices and descriptions\n",
    "food_choices = {\n",
    "    \"Hainanese Chicken Rice\": \"Hainanese chicken rice is a beloved dish consisting of tender poached chicken served with flavorful rice, accompanied by chili sauce and ginger paste. The chicken is typically succulent and infused with subtle aromas, while the rice is rich in flavor from being cooked in chicken broth.\",\n",
    "    \"Laksa\": \"Laksa is a spicy noodle soup with a rich and creamy coconut curry broth. It's typically served with rice noodles and topped with shrimp, fish cakes, bean sprouts, and a hard-boiled egg. The broth is flavorful and aromatic, with a perfect balance of spice and creaminess.\",\n",
    "    \"Char Kway Teow\": \"Char Kway Teow is a popular stir-fried noodle dish known for its smoky flavor and savory sauce. It features flat rice noodles cooked with Chinese sausage, shrimp, cockles, bean sprouts, and chives, all stir-fried in a flavorful dark soy sauce-based seasoning.\",\n",
    "    \"Chilli Crab\": \"Chilli Crab is a quintessential Singaporean seafood dish featuring mud crab cooked in a tangy and spicy chili sauce. The sauce is rich and flavorful, with hints of sweetness from the tomato paste and a kick of heat from the chili. It's often enjoyed with mantou (fried buns) for dipping.\",\n",
    "    \"Satay\": \"Satay is a popular street food in Singapore consisting of skewered and grilled meat served with a flavorful peanut sauce. The meat is marinated in a blend of spices, then grilled to perfection, resulting in tender and juicy skewers. It's often served with cucumber slices and rice cakes.\",\n",
    "    \"Roti Prata\": \"Roti Prata is a crispy and flaky flatbread that originated from Indian cuisine but has become a favorite in Singapore. It's typically served with a side of savory curry dipping sauce, which complements the buttery and crispy texture of the prata.\",\n",
    "    \"Nasi Lemak\": \"Nasi Lemak is a traditional Malay dish known for its fragrant coconut rice served with an array of flavorful accompaniments. It's often accompanied by fried chicken or fish, sambal chili for heat, fried anchovies and roasted peanuts for crunch, cucumber slices for freshness, and a hard-boiled egg for protein.\",\n",
    "    \"Mee Goreng\": \"Mee Goreng is a flavorful and spicy stir-fried noodle dish with origins in Indian and Malay cuisine. It features yellow noodles stir-fried with a variety of vegetables, tofu, shrimp, and a spicy and tangy sauce made from a blend of chili, tomato, and spices.\",\n",
    "    \"Bak Kut Teh\": \"Bak Kut Teh, which translates to \\\"meat bone tea,\\\" is a comforting soup dish consisting of tender pork ribs simmered in a flavorful broth of Chinese herbs and spices. The broth is rich and aromatic, with layers of flavor from ingredients like garlic, pepper, and star anise.\",\n",
    "    \"Hokkien Mee\": \"Hokkien Mee is a popular noodle dish in Singapore made from a mix of yellow and rice noodles stir-fried with seafood, such as shrimp and squid, and vegetables like cabbage and bean sprouts. The dish is infused with a rich seafood flavor from the broth, resulting in a hearty and satisfying meal.\",\n",
    "    \"Bak Chor Mee\": \"Bak Chor Mee is a flavorful noodle dish featuring springy egg noodles tossed in a spicy vinegar sauce and topped with minced pork, pork slices, mushrooms, and meatballs. The combination of savory, tangy, and spicy flavors makes it a favorite among noodle lovers.\",\n",
    "    \"Murtabak\": \"Murtabak is a savory pancake of Arab origin that has become popular in Singapore. It's made from thin, flaky pastry filled with a mixture of minced meat, onions, and egg, then folded and grilled to perfection. It's often served with a side of curry dipping sauce for added flavor.\",\n",
    "    \"Kaya Toast\": \"Kaya Toast is a classic Singaporean breakfast dish consisting of toasted bread spread with kaya, a sweet and creamy coconut and egg jam, and butter. It's typically served with soft-boiled eggs and a cup of coffee or tea, making it a comforting and delicious start to the day.\",\n",
    "    \"Rojak\": \"Rojak is a traditional fruit and vegetable salad dish popular in Singapore and Malaysia. It features a mix of crunchy fruits and vegetables tossed in a sweet and spicy shrimp paste sauce, then topped with crushed peanuts and sesame seeds for added texture and flavor.\",\n",
    "    \"Nasi Padang\": \"Nasi Padang is an Indonesian rice dish that has become popular in Singapore. It consists of steamed rice served with a variety of flavorful and spicy dishes, such as rendang, sambal goreng, and sayur lodeh. It's a feast for the senses, with a mix of bold flavors and aromatic spices.\",\n",
    "    \"Biryani\": \"Biryani is a fragrant and flavorful rice dish of South Asian origin that has become popular in Singapore. It features long-grain basmati rice cooked with a blend of aromatic spices, layered with tender meat (chicken, mutton, or beef), and served with a side of cooling yogurt-based raita.\",\n",
    "    \"Otah-Otah\": \"Otah-Otah is a traditional Malay dish made from spicy fish paste mixed with herbs and spices, then wrapped in banana leaves and grilled or steamed until cooked through. It's a flavorful and aromatic dish with a perfect balance of spice and sweetness from the banana leaves.\",\n",
    "    \"Kueh Pie Tee\": \"Kueh Pie Tee is a popular Peranakan snack in Singapore made from crispy pastry cups filled with a savory mixture of shredded turnips, carrots, and prawns, then topped with chili sauce and fried shallots. It's a delightful combination of textures and flavors, with a hint of sweetness from the turnips.\",\n",
    "    \"Tau Huay\": \"Tau Huay, also known as tofu pudding or douhua, is a comforting dessert popular in Singapore. It's made from soft and silky smooth tofu pudding served with a sweet syrup, often flavored with pandan leaves or ginger for added fragrance. It's a light and refreshing dessert perfect for a hot day.\",\n",
    "    \"Chwee Kueh\": \"Chwee Kueh is a classic Teochew snack in Singapore made from steamed rice cakes topped with a savory mixture of preserved radish (chye poh) and fried shallots. It's typically served with a side of spicy chili sauce for added flavor and heat. The soft and slightly chewy texture of the rice cakes contrasts beautifully with the crunchy toppings.\",\n",
    "    \"Mee Siam\": \"Mee Siam is a flavorful noodle dish with Malay and Thai influences, popular in Singapore. It features rice vermicelli noodles cooked in a spicy, sweet, and tangy gravy, served with prawns, tofu, hard-boiled egg, and bean sprouts. It's a vibrant and satisfying dish with a perfect balance of flavors.\",\n",
    "    \"Kway Chap\": \"Kway Chap is a comforting noodle soup dish of Teochew origin popular in Singapore. It features wide rice noodles served in a rich and aromatic broth made from pork bones and various spices, accompanied by tender braised pork, tofu, hard-boiled eggs, and offal. It's a hearty and flavorful meal that's perfect for any time of the day.\",\n",
    "    \"Putu Piring\": \"Putu Piring is a traditional Malay dessert in Singapore made from steamed rice flour cakes filled with gooey gula melaka (palm sugar) and served with freshly grated coconut. It's a sweet and fragrant treat with a melt-in-your-mouth texture, perfect for satisfying your sweet tooth.\",\n",
    "    \"Bak Kwa\": \"Bak Kwa is a popular Chinese New Year snack in Singapore made from grilled slices of sweet and savory dried meat, typically pork or beef. The meat is thinly sliced and marinated in a blend of spices and sugar before being grilled to perfection, resulting in a tender and flavorful snack that's irresistible.\",\n",
    "    \"Ice Kachang\": \"Ice Kachang is a beloved dessert in Singapore made from shaved ice topped with colorful syrup, sweetened condensed milk, red beans, attap chee (palm seed), grass jelly, and corn. It's a refreshing and sweet treat that's perfect for cooling down on a hot day.\"\n",
    "}\n",
    "\n",
    "\n",
    "# # Function to display food choices and get user input\n",
    "# def select_food_choice():\n",
    "#     print(\"Select a food choice:\")\n",
    "#     for index, (food, description) in enumerate(food_choices.items(), start=1):\n",
    "#         print(f\"{index}. {food} - {description}\")\n",
    "# \n",
    "#     # Get user choice\n",
    "#     choice_index = input(\"Enter the number of your choice: \")\n",
    "#     try:\n",
    "#         choice_index = int(choice_index)\n",
    "#         if 1 <= choice_index <= len(food_choices):\n",
    "#             return list(food_choices.keys())[choice_index - 1]\n",
    "#         else:\n",
    "#             print(\"Invalid choice. Please enter a number between 1 and\", len(food_choices))\n",
    "#             return select_food_choice()  # Ask again for valid input\n",
    "#     except ValueError:\n",
    "#         print(\"Invalid input. Please enter a number.\")\n",
    "#         return select_food_choice()  # Ask again for valid input\n",
    "\n",
    "# In[14]:\n",
    "\n",
    "\n",
    "# Function to display food choices and get user input\n",
    "def select_food_choices(num_choices=3):\n",
    "    print(\"Select\", num_choices, \"food choices:\")\n",
    "    selected_foods = []\n",
    "    for i in range(num_choices):\n",
    "        print(\"Choice\", i+1)\n",
    "        for index, (food, description) in enumerate(food_choices.items(), start=1):\n",
    "            print(f\"{index}. {food} - {description}\")\n",
    "\n",
    "        # Get user choice\n",
    "        choice_index = input(\"Enter the number of your choice: \")\n",
    "        try:\n",
    "            choice_index = int(choice_index)\n",
    "            if 1 <= choice_index <= len(food_choices):\n",
    "                selected_foods.append(list(food_choices.keys())[choice_index - 1])\n",
    "            else:\n",
    "                print(\"Invalid choice. Please enter a number between 1 and\", len(food_choices))\n",
    "                return select_food_choices(num_choices)  # Ask again for valid input\n",
    "        except ValueError:\n",
    "            print(\"Invalid input. Please enter a number.\")\n",
    "            return select_food_choices(num_choices)  # Ask again for valid input\n",
    "    return selected_foods\n",
    "\n",
    "\n",
    "# In[15]:\n",
    "\n",
    "\n",
    "# Welcome message and food choices\n",
    "print(\"Welcome to the food recommender system!\")\n",
    "print(\"Select 3 food choices:\")\n",
    "\n",
    "# Display food choices\n",
    "for i, food in enumerate(food_choices.keys(), start=1):\n",
    "    print(f\"{i}. {food} - {food_choices[food]}\")\n",
    "\n",
    "# Prompt user to choose 3 foods\n",
    "selected_foods = []\n",
    "while len(selected_foods) < 3:\n",
    "    choice = input(\"\\nEnter the number of your choice: \")\n",
    "    if choice.isdigit():\n",
    "        choice = int(choice)\n",
    "        if 1 <= choice <= len(food_choices):\n",
    "            food = list(food_choices.keys())[choice - 1]\n",
    "            if food not in selected_foods:\n",
    "                selected_foods.append(food)\n",
    "            else:\n",
    "                print(\"You have already selected this food. Please choose a different one.\")\n",
    "        else:\n",
    "            print(\"Invalid choice. Please enter a number within the range.\")\n",
    "    else:\n",
    "        print(\"Invalid input. Please enter a number.\")\n",
    "\n",
    "# Find the closest review for each selected food\n",
    "closest_food = None\n",
    "max_similarity_percent = -1\n",
    "\n",
    "for food in selected_foods:\n",
    "    food_description = food_choices[food]\n",
    "    closest_sentence, closest_similarity_percent = find_closest_sentence(food_description, data)\n",
    "    print(\"\\nFor\", food, \":\")\n",
    "    print(\"Closest Review:\", closest_sentence)\n",
    "    print(\"Cosine Similarity Percentage:\", format(closest_similarity_percent, '.2%'))\n",
    "    \n",
    "    # Keep track of the food with the highest similarity percentage\n",
    "    if closest_similarity_percent > max_similarity_percent:\n",
    "        max_similarity_percent = closest_similarity_percent\n",
    "        closest_food = food\n",
    "\n",
    "# Combine descriptions of selected foods\n",
    "combined_description = \" \".join([food_choices[food] for food in selected_foods])\n",
    "\n",
    "# Find closest review based on combined description\n",
    "closest_review = None\n",
    "max_similarity_percent_combined = -1\n",
    "\n",
    "for index, row in data.iterrows():\n",
    "    sentence_vector = row['sentence_vector']\n",
    "    similarity = cosine_similarity([get_sentence_vector(combined_description)], [sentence_vector])[0][0]\n",
    "    if similarity > max_similarity_percent_combined:\n",
    "        max_similarity_percent_combined = similarity\n",
    "        closest_review = row['Title']\n",
    "\n",
    "# Display the food with the highest similarity percentage and closest review based on selected foods\n",
    "print(\"\\nFood with the highest similarity percentage:\", closest_food)\n",
    "print(\"\\nClosest Review based on selected foods:\")\n",
    "print(\"Review:\", closest_review)\n",
    "print(\"Cosine Similarity Percentage:\", format(max_similarity_percent_combined, '.2%'))\n",
    "\n",
    "\n",
    "# # Get description of selected foods and find closest sentence for each\n",
    "# for food in selected_foods:\n",
    "#     food_description = food_choices[food]\n",
    "#     closest_sentence, closest_similarity_percent = find_closest_sentence(food_description, data)\n",
    "#     print(\"\\nFor\", food, \":\")\n",
    "#     print(\"Closest Review:\", closest_sentence)\n",
    "#     print(\"Cosine Similarity Percentage:\", format(closest_similarity_percent, '.2%'))\n",
    "\n",
    "# # Example usage:\n",
    "# print(\"Welcome to the food recommender system!\")\n",
    "# selected_food = select_food_choice()\n",
    "# print(\"Selected food:\", selected_food)\n",
    "# \n",
    "# # Get description of selected food and find closest sentence\n",
    "# food_description = food_choices[selected_food]\n",
    "# closest_sentence, closest_similarity_percent = find_closest_sentence(food_description, data)\n",
    "# print(\"Closest Review:\", closest_sentence)\n",
    "# print(\"Cosine Similarity Percentage:\", closest_similarity_percent)\n",
    "\n",
    "# # Example usage:\n",
    "# print(\"Enter your preference\")\n",
    "# input_text = input()\n",
    "# \n",
    "# closest_sentence = find_closest_sentence(input_text, data)\n",
    "# print(\"Closest Review:\", closest_sentence)\n",
    "\n",
    "def main():\n",
    "    st.title(\"Whisky Recommender\")\n",
    "\n",
    "    # Add Streamlit UI components and interactions here\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    main()\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
